# Finnish 

In [11]:
from nltk.corpus import stopwords #you can remove stop words for speed
from nltk.cluster.util import cosine_distance
import numpy as np
import networkx as nx

In [4]:
!python -m spacy download fi_core_news_sm

import spacy

# Load the Finnish language model
nlp = spacy.load("fi_core_news_sm")


     ---------------------------------------- 0.0/14.3 MB ? eta -:--:--
     ---------------------------------------- 0.0/14.3 MB ? eta -:--:--
     ---------------------------------------- 0.0/14.3 MB ? eta -:--:--
     ---------------------------------------- 0.0/14.3 MB ? eta -:--:--
     ---------------------------------------- 0.0/14.3 MB ? eta -:--:--
     --------------------------------------- 0.0/14.3 MB 178.6 kB/s eta 0:01:21
     --------------------------------------- 0.1/14.3 MB 272.3 kB/s eta 0:00:53
     --------------------------------------- 0.1/14.3 MB 306.3 kB/s eta 0:00:47
     --------------------------------------- 0.1/14.3 MB 306.3 kB/s eta 0:00:47
     --------------------------------------- 0.1/14.3 MB 306.3 kB/s eta 0:00:47
     --------------------------------------- 0.1/14.3 MB 300.4 kB/s eta 0:00:48
     --------------------------------------- 0.1/14.3 MB 315.4 kB/s eta 0:00:46
     --------------------------------------- 0.2/14.3 MB 327.3 kB/s eta 0:00:44


In [37]:
file = open("C:\\Users\\Dell\\OneDrive\\Desktop\\TextBasedAnalysis\\Text1.txt", "r")

# This file contains one paragraph with multiple sentences
filedata = file.readlines()

article = filedata[0].split(". ")  # Process only the first paragraph

sentences = []

for sentence in article:
    print(sentence)
    doc = nlp(sentence)
    words = [token.text for token in doc]
    sentences.append(words)

Suomen kieli on yksi maailman vaikeimmista kielistä, mutta samalla myös yksi kauneimmista ja ilmaisuvoimaisimmista
Se kuuluu suomalais-ugrilaiseen kieliperheeseen yhdessä viron ja unkarin kanssa
Suomen kielessä on paljon erityispiirteitä, jotka tekevät siitä ainutlaatuisen ja mielenkiintoisen.



In [38]:
print("Sentences are ", sentences)

Sentences are  [['Suomen', 'kieli', 'on', 'yksi', 'maailman', 'vaikeimmista', 'kielistä', ',', 'mutta', 'samalla', 'myös', 'yksi', 'kauneimmista', 'ja', 'ilmaisuvoimaisimmista'], ['Se', 'kuuluu', 'suomalais-ugrilaiseen', 'kieliperheeseen', 'yhdessä', 'viron', 'ja', 'unkarin', 'kanssa'], ['Suomen', 'kielessä', 'on', 'paljon', 'erityispiirteitä', ',', 'jotka', 'tekevät', 'siitä', 'ainutlaatuisen', 'ja', 'mielenkiintoisen', '.', '\n']]


In [39]:
def sentence_similarity(sent1, sent2 ):
    sent1 = [w.lower() for w in sent1]
    sent2 = [w.lower() for w in sent2]
    all_words = list(set(sent1 + sent2))
    vector1 = [0] * len(all_words)
    vector2 = [0] * len(all_words)
     # build the vector for the first sentence
    for w in sent1:
          vector1[all_words.index(w)] += 1
     # build the vector for the second sentence
    for w in sent2:
          vector2[all_words.index(w)] += 1
    return 1 - cosine_distance(vector1, vector2)

In [40]:
import numpy as np
similarity_matrix = np.zeros((len(sentences), len(sentences)))
 
for idx1 in range(len(sentences)):
        for idx2 in range(len(sentences)):
             if idx1 == idx2: #ignore if both are same sentences
                continue 
             similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1], sentences[idx2])

print("Smilarity matrix \n", similarity_matrix)


Smilarity matrix 
 [[0.         0.08084521 0.25928149]
 [0.08084521 0.         0.08908708]
 [0.25928149 0.08908708 0.        ]]


In [41]:
# Step 3 - Rank sentences in similarity martix
sentence_similarity_graph = nx.from_numpy_array(similarity_matrix)
scores = nx.pagerank(sentence_similarity_graph)
print("scores", scores)

scores {0: 0.3880970037531015, 1: 0.21474050252752702, 2: 0.3971624937193709}


In [42]:
# Step 4 - Sort the rank and pick top sentences
ranked_sentence = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)    
print("Indexes of top ranked_sentence order are \n\n", ranked_sentence)


Indexes of top ranked_sentence order are 

 [(0.3971624937193709, ['Suomen', 'kielessä', 'on', 'paljon', 'erityispiirteitä', ',', 'jotka', 'tekevät', 'siitä', 'ainutlaatuisen', 'ja', 'mielenkiintoisen', '.', '\n']), (0.3880970037531015, ['Suomen', 'kieli', 'on', 'yksi', 'maailman', 'vaikeimmista', 'kielistä', ',', 'mutta', 'samalla', 'myös', 'yksi', 'kauneimmista', 'ja', 'ilmaisuvoimaisimmista']), (0.21474050252752702, ['Se', 'kuuluu', 'suomalais-ugrilaiseen', 'kieliperheeseen', 'yhdessä', 'viron', 'ja', 'unkarin', 'kanssa'])]


In [44]:
#Step 5 - How many sentences to pick
n = int(input("How many sentences do you want in the summary? "))
#n=2
summarize_text = []
for i in range(n):
      summarize_text.append(" ".join(ranked_sentence[i][1]))



How many sentences do you want in the summary?  3


In [45]:
# Step 6 - Offcourse, output the summarize text
print("Summarize Text: \n", ". ".join(summarize_text))

Summarize Text: 
 Suomen kielessä on paljon erityispiirteitä , jotka tekevät siitä ainutlaatuisen ja mielenkiintoisen . 
. Suomen kieli on yksi maailman vaikeimmista kielistä , mutta samalla myös yksi kauneimmista ja ilmaisuvoimaisimmista. Se kuuluu suomalais-ugrilaiseen kieliperheeseen yhdessä viron ja unkarin kanssa


# Chinese

In [17]:
!python -m spacy download fi_core_news_sm

import spacy

# Load the Finnish language model
nlp = spacy.load("zh_core_web_lg")


     ---------------------------------------- 0.0/14.3 MB ? eta -:--:--
     ---------------------------------------- 0.1/14.3 MB 2.3 MB/s eta 0:00:07
     ---------------------------------------- 0.1/14.3 MB 1.6 MB/s eta 0:00:10
      --------------------------------------- 0.3/14.3 MB 2.0 MB/s eta 0:00:07
     - -------------------------------------- 0.4/14.3 MB 2.3 MB/s eta 0:00:07
     - -------------------------------------- 0.5/14.3 MB 2.2 MB/s eta 0:00:07
     - -------------------------------------- 0.6/14.3 MB 2.2 MB/s eta 0:00:07
     -- ------------------------------------- 0.8/14.3 MB 2.3 MB/s eta 0:00:06
     -- ------------------------------------- 0.8/14.3 MB 2.3 MB/s eta 0:00:06
     -- ------------------------------------- 0.8/14.3 MB 2.1 MB/s eta 0:00:07
     -- ------------------------------------- 0.9/14.3 MB 2.0 MB/s eta 0:00:07
     -- ------------------------------------- 1.0/14.3 MB 1.9 MB/s eta 0:00:07
     --- ------------------------------------ 1.1/14.3 MB 2

OSError: [E050] Can't find model 'zh_core_web_lg'. It doesn't seem to be a Python package or a valid path to a data directory.

In [19]:
file = open("C:\\Users\\Dell\\OneDrive\\Desktop\\TextBasedAnalysis\\chinese.txt", "r", encoding="utf-8")

# This file contains one paragraph with multiple sentences
filedata = file.readlines()

article = filedata[0].split("。")  # Process only the first paragraph, split on Chinese period "。"

sentences = []

for sentence in article:
    print(sentence)
    doc = nlp(sentence)
    words = [token.text for token in doc]
    sentences.append(words)

这是一个由50行组成的中文段落
在这个段落中,我们将探讨人工智能技术的发展及其对社会的影响
人工智能是计算机科学的一个重要分支,它的目标是创造能够模拟人类智能的机器
近年来,人工智能技术取得了长足的进步,在许多领域都有着广泛的应用,如自然语言处理、计算机视觉、机器学习等
这些技术的发展为我们的生活带来了诸多便利,同时也引发了一些伦理和社会问题




In [20]:
print("Sentences are ", sentences)

Sentences are  [['这是一个由50行组成的中文段落'], ['在这个段落中', ',', '我们将探讨人工智能技术的发展及其对社会的影响'], ['人工智能是计算机科学的一个重要分支', ',', '它的目标是创造能够模拟人类智能的机器'], ['近年来', ',', '人工智能技术取得了长足的进步', ',', '在许多领域都有着广泛的应用', ',', '如自然语言处理、计算机视觉、机器学习等'], ['这些技术的发展为我们的生活带来了诸多便利', ',', '同时也引发了一些伦理和社会问题'], ['\n']]


In [21]:
def sentence_similarity(sent1, sent2 ):
    sent1 = [w.lower() for w in sent1]
    sent2 = [w.lower() for w in sent2]
    all_words = list(set(sent1 + sent2))
    vector1 = [0] * len(all_words)
    vector2 = [0] * len(all_words)
     # build the vector for the first sentence
    for w in sent1:
          vector1[all_words.index(w)] += 1
     # build the vector for the second sentence
    for w in sent2:
          vector2[all_words.index(w)] += 1
    return 1 - cosine_distance(vector1, vector2)

In [22]:
import numpy as np
similarity_matrix = np.zeros((len(sentences), len(sentences)))
 
for idx1 in range(len(sentences)):
        for idx2 in range(len(sentences)):
             if idx1 == idx2: #ignore if both are same sentences
                continue 
             similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1], sentences[idx2])

print("Smilarity matrix \n", similarity_matrix)


Smilarity matrix 
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.33333333 0.48038446 0.33333333 0.        ]
 [0.         0.33333333 0.         0.48038446 0.33333333 0.        ]
 [0.         0.48038446 0.48038446 0.         0.48038446 0.        ]
 [0.         0.33333333 0.33333333 0.48038446 0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [23]:
# Step 3 - Rank sentences in similarity martix
sentence_similarity_graph = nx.from_numpy_array(similarity_matrix)
scores = nx.pagerank(sentence_similarity_graph)
print("scores", scores)

scores {0: 0.03488384541998177, 1: 0.22009878393430723, 2: 0.22009878393430723, 3: 0.26993595735711473, 4: 0.22009878393430723, 5: 0.03488384541998177}


In [24]:
# Step 4 - Sort the rank and pick top sentences
ranked_sentence = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)    
print("Indexes of top ranked_sentence order are \n\n", ranked_sentence)


Indexes of top ranked_sentence order are 

 [(0.26993595735711473, ['近年来', ',', '人工智能技术取得了长足的进步', ',', '在许多领域都有着广泛的应用', ',', '如自然语言处理、计算机视觉、机器学习等']), (0.22009878393430723, ['这些技术的发展为我们的生活带来了诸多便利', ',', '同时也引发了一些伦理和社会问题']), (0.22009878393430723, ['在这个段落中', ',', '我们将探讨人工智能技术的发展及其对社会的影响']), (0.22009878393430723, ['人工智能是计算机科学的一个重要分支', ',', '它的目标是创造能够模拟人类智能的机器']), (0.03488384541998177, ['这是一个由50行组成的中文段落']), (0.03488384541998177, ['\n'])]


In [26]:
#Step 5 - How many sentences to pick
n = int(input("How many sentences do you want in the summary? "))
#n=2
summarize_text = []
for i in range(n):
      summarize_text.append(" ".join(ranked_sentence[i][1]))



How many sentences do you want in the summary?  4


In [27]:
# Step 6 - Offcourse, output the summarize text
print("Summarize Text: \n", ". ".join(summarize_text))

Summarize Text: 
 近年来 , 人工智能技术取得了长足的进步 , 在许多领域都有着广泛的应用 , 如自然语言处理、计算机视觉、机器学习等. 这些技术的发展为我们的生活带来了诸多便利 , 同时也引发了一些伦理和社会问题. 在这个段落中 , 我们将探讨人工智能技术的发展及其对社会的影响. 人工智能是计算机科学的一个重要分支 , 它的目标是创造能够模拟人类智能的机器


# Japanese

In [28]:
!python -m spacy download fi_core_news_sm

import spacy

# Load the Finnish language model
nlp = spacy.load("ja_core_news_lg")

     ---------------------------------------- 0.0/14.3 MB ? eta -:--:--
     ---------------------------------------- 0.0/14.3 MB ? eta -:--:--
     ---------------------------------------- 0.0/14.3 MB ? eta -:--:--
     ---------------------------------------- 0.0/14.3 MB ? eta -:--:--
     --------------------------------------- 0.0/14.3 MB 187.9 kB/s eta 0:01:17
     --------------------------------------- 0.0/14.3 MB 178.6 kB/s eta 0:01:21
     --------------------------------------- 0.1/14.3 MB 350.1 kB/s eta 0:00:41
     --------------------------------------- 0.1/14.3 MB 500.5 kB/s eta 0:00:29
      -------------------------------------- 0.3/14.3 MB 787.7 kB/s eta 0:00:18
      -------------------------------------- 0.3/14.3 MB 873.8 kB/s eta 0:00:17
     - -------------------------------------- 0.5/14.3 MB 1.2 MB/s eta 0:00:12
     - -------------------------------------- 0.6/14.3 MB 1.3 MB/s eta 0:00:11
     - -------------------------------------- 0.6/14.3 MB 1.2 MB/s eta 0:0

OSError: [E050] Can't find model 'ja_core_news_lg'. It doesn't seem to be a Python package or a valid path to a data directory.

In [29]:
file = open("C:\\Users\\Dell\\OneDrive\\Desktop\\TextBasedAnalysis\\japanese.txt", "r", encoding="utf-8")

# This file contains one paragraph with multiple sentences
filedata = file.readlines()

article = filedata[0].split("。")  # Process only the first paragraph, split on Chinese period "。"

sentences = []

for sentence in article:
    print(sentence)
    doc = nlp(sentence)
    words = [token.text for token in doc]
    sentences.append(words)

日本語は、日本で話されている言語であり、世界で最も複雑な言語の1つとして知られています
日本語の文法構造は、英語などの西洋言語とは大きく異なります
例えば、日本語では主語が省略されることが多く、動詞が文の最後に置かれます
また、敬語の使い方が非常に重要で、相手との関係性に応じて適切な敬語を使い分ける必要があります




In [30]:
print("Sentences are ", sentences)

Sentences are  [['日本語は、日本で話されている言語であり、世界で最も複雑な言語の1つとして知られています'], ['日本語の文法構造は、英語などの西洋言語とは大きく異なります'], ['例えば、日本語では主語が省略されることが多く、動詞が文の最後に置かれます'], ['また、敬語の使い方が非常に重要で、相手との関係性に応じて適切な敬語を使い分ける必要があります'], ['\n']]


In [31]:
def sentence_similarity(sent1, sent2 ):
    sent1 = [w.lower() for w in sent1]
    sent2 = [w.lower() for w in sent2]
    all_words = list(set(sent1 + sent2))
    vector1 = [0] * len(all_words)
    vector2 = [0] * len(all_words)
     # build the vector for the first sentence
    for w in sent1:
          vector1[all_words.index(w)] += 1
     # build the vector for the second sentence
    for w in sent2:
          vector2[all_words.index(w)] += 1
    return 1 - cosine_distance(vector1, vector2)


In [32]:
similarity_matrix = np.zeros((len(sentences), len(sentences)))
 
for idx1 in range(len(sentences)):
        for idx2 in range(len(sentences)):
             if idx1 == idx2: #ignore if both are same sentences
                continue 
             similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1], sentences[idx2])

print("Smilarity matrix \n", similarity_matrix)


Smilarity matrix 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [33]:
# Step 3 - Rank sentences in similarity martix
sentence_similarity_graph = nx.from_numpy_array(similarity_matrix)
scores = nx.pagerank(sentence_similarity_graph)
print("scores", scores)


scores {0: 0.2, 1: 0.2, 2: 0.2, 3: 0.2, 4: 0.2}


In [34]:
# Step 4 - Sort the rank and pick top sentences
ranked_sentence = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)    
print("Indexes of top ranked_sentence order are \n\n", ranked_sentence)


Indexes of top ranked_sentence order are 

 [(0.2, ['日本語は、日本で話されている言語であり、世界で最も複雑な言語の1つとして知られています']), (0.2, ['日本語の文法構造は、英語などの西洋言語とは大きく異なります']), (0.2, ['例えば、日本語では主語が省略されることが多く、動詞が文の最後に置かれます']), (0.2, ['また、敬語の使い方が非常に重要で、相手との関係性に応じて適切な敬語を使い分ける必要があります']), (0.2, ['\n'])]


In [35]:
#Step 5 - How many sentences to pick
n = int(input("How many sentences do you want in the summary? "))
#n=2
summarize_text = []
for i in range(n):
      summarize_text.append(" ".join(ranked_sentence[i][1]))


How many sentences do you want in the summary?  5


In [36]:
# Step 6 - Offcourse, output the summarize text
print("Summarize Text: \n", ". ".join(summarize_text))

Summarize Text: 
 日本語は、日本で話されている言語であり、世界で最も複雑な言語の1つとして知られています. 日本語の文法構造は、英語などの西洋言語とは大きく異なります. 例えば、日本語では主語が省略されることが多く、動詞が文の最後に置かれます. また、敬語の使い方が非常に重要で、相手との関係性に応じて適切な敬語を使い分ける必要があります. 

